### ISSUE TITLE
bridge.msh  vs bridge.geo

### ISSUE THREAD

**Issue by cromlyngames** [salazardetroya/bridge_post#2]
bridge.py  (line 49)  loads the geometry from a file called bridge.msh
The repo appears to have that info stored in a file called bridge.geo

bridge.geo does not appear to be called by any of the scripts in the repo

**Comment by salazardetroya** [comment]
You need to generate the mesh with [gmsh](https://gmsh.info/). You can open the .geo file with gmsh and generate the mesh there or directly run it from your command line as
```
gmsh -2 bridge.geo
```
